environment:
  name: "Centipede"
  height: 84
  width: 84
  frame_skip: 4
  frame_stack: 8
  max_episode_steps: 2700
  gray_scale: True 
  clip_reward: True 
  done_on_life_loss: True 
  noop_max: 30
  terminal_on_life_loss: True
  episodic_life: True


operational:
  num_actors: 6
  num_training_steps: 1e5
  batch_size: 128
  seed: 489 
  clip_grad: True
  samples_save_frequency: -1
  samples_save_dir: None
  use_tensorboard: False
  clip_grads: True



memory:
  replay_capacity: 1e6
  min_replay_size: 1e4
  priority_exponent: 0.0
  importance_sampling_exponent: 0.0


model:
  num_res_blocks: 
  num_planes:
  value_support_size: 
  reward_support_size: 

output_dir: None