
BATCH_SIZE: 32
GAMMA: 0.99
EPS_START: 0.8
EPS_END: 0.02
EPS_DECAY: 5e4
RENDER: False
LR: 3e-4
INITIAL_MEMORY: 10000
MEMORY_SIZE_FACTOR: 10
ENV_NAME: "ALE/Centipede-v5"
N_STACK: 4
TOTAL_STEPS: 1e5
TARGET_UPDATE: 500
RENDER_TEST: False

BIN_REWARD: True
head:
  HIDDEN_DIM: 1024
test:
  N_EPISODES: 25
  RENDER_TEST: False

