
BATCH_SIZE: 32
GAMMA: 0.99
EPS_START: 1.0
EPS_END: 0.02
EPS_DECAY: 5e5
RENDER: False
LR: 3e-4
INITIAL_MEMORY: 10000
MEMORY_SIZE_FACTOR: 10
ENV_NAME: "ALE/Centipede-v5"
N_STACK: 4
TOTAL_STEPS: 1e6
RENDER_TEST: False

TARGET_UPDATE: 1000


BIN_REWARD: True
head:
  HIDDEN_DIM: 512
test:
  N_EPISODES: 25
  RENDER_TEST: False

